# Generated by Django 3.2.7 on 2021-11-27 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_phone_socialmedia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='phone',
            options={'verbose_name': 'Phone', 'verbose_name_plural': 'Phones'},
        ),
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'verbose_name': 'SocialMedia', 'verbose_name_plural': 'SocialMedias'},
        ),
    ]
