# Generated by Django 3.1.3 on 2021-12-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_auto_20211215_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.CharField(max_length=128, verbose_name='Aдрес'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на адрес'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Почта'),
        ),
    ]
