# Generated by Django 3.2.7 on 2021-11-20 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accommodation', to='tours.tour'),
        ),
        migrations.CreateModel(
            name='DataPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('status', models.CharField(choices=[('Sold out', 'Sold Out'), ('Completed', 'Completed'), ('Available', 'Available')], default='Available', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_prices', to='tours.tour')),
            ],
        ),
    ]
