# Generated by Django 3.2.7 on 2021-11-27 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_auto_20211120_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(blank=True, default='00-00-0000', null=True)),
                ('end', models.DateTimeField(blank=True, default='00-00-0000', null=True)),
                ('min_people', models.PositiveIntegerField()),
                ('max_people', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Sold out', 'Sold Out'), ('Completed', 'Completed'), ('Available', 'Available'), ('Guaranteed', 'Guaranteed')], default='Available', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_prices', to='tours.tour')),
            ],
        ),
        migrations.DeleteModel(
            name='DataPrice',
        ),
    ]
