# Generated by Django 3.2.7 on 2021-11-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_auto_20211127_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateprice',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dateprice',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
