# Generated by Django 3.2.7 on 2021-11-28 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_alter_category_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
    ]
