# Generated by Django 3.1.3 on 2021-12-17 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0010_auto_20211215_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='body_list',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Название'),
        ),
    ]
