# Generated by Django 3.1.3 on 2021-12-17 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0011_auto_20211217_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tour_pictures/%Y/%m/%d/', verbose_name='Основная фотография'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='body_list',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Краткое описание'),
        ),
    ]
