# Generated by Django 3.1.3 on 2021-12-17 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0012_auto_20211217_0347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourphoto',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Галерея'},
        ),
        migrations.AddField(
            model_name='tour',
            name='is_top',
            field=models.BooleanField(default=False, verbose_name='Топ'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tour_pictures/%Y/%m/%d/', verbose_name='Основное изображение'),
        ),
    ]
