# Generated by Django 3.1.3 on 2021-12-17 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0013_auto_20211217_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateprice',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_prices', to='tours.tour', verbose_name='Тур'),
        ),
    ]
